# Generated by Django 4.2.13 on 2024-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="system_users/"),
        ),
    ]
