# Generated by Django 4.2.13 on 2024-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile_api", "0002_systemuser_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("thumbnail", models.ImageField(upload_to="lessons_thumbnails")),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
    ]
